const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const defaultState = {
  onboarded:false, route:'welcome', name:'Alex', goal:'Reduce screen time', vault:50, duration:21,
  selectedApps:['Instagram','TikTok','YouTube','X','Reddit'], limits:{Instagram:90,TikTok:60,YouTube:60,X:30,Reddit:30,Safari:30},
  focusRunning:false, focusRemaining:1476, protected:18, spent:6.5, streak:5
};
function loadState(){
  try {
    const saved = JSON.parse(localStorage.getItem('aurea_state') || 'null');
    if(!saved || typeof saved !== 'object') return {...defaultState};
    return {
      ...defaultState,
      ...saved,
      selectedApps: Array.isArray(saved.selectedApps) ? saved.selectedApps : [...defaultState.selectedApps],
      limits: {...defaultState.limits, ...(saved.limits || {})}
    };
  } catch (error) {
    localStorage.removeItem('aurea_state');
    return {...defaultState};
  }
}
const state = loadState();
let timer = null;
const apps = [
  ['Instagram','ig','◎','1h 12m',75], ['TikTok','tt','♪','58m',58], ['YouTube','yt','▶','43m',43],
  ['X','x','𝕏','32m',106], ['Reddit','rd','r','18m',60], ['Facebook','fb','f','12m',40], ['Safari','sf','◌','8m',26], ['Games','gm','🎮','4m',13]
];
function save(){ localStorage.setItem('aurea_state', JSON.stringify(state)); }
function toast(t){ const el=$('#toast'); el.textContent=t; el.classList.add('show'); clearTimeout(el._t); el._t=setTimeout(()=>el.classList.remove('show'),1800); }
function money(n){ return '$' + Number(n).toFixed(2); }
function icon(cls, label, glyph){ return `<span class="appicon ${cls}">${glyph}</span>`; }
function appTop(title='', subtitle='', back=false, right=''){ return `<div class="top">${back?`<button class="back" onclick="go('${back}')">‹</button>`:'<span></span>'}<div style="flex:1"><h1 class="title">${title}</h1>${subtitle?`<p class="subtitle">${subtitle}</p>`:''}</div>${right||'<span></span>'}</div>`; }
function screen(html, tabs=true){ $('#view').innerHTML = `<section class="screen ${tabs?'':'no-tabs'}">${html}</section>`; $('#tabbar').classList.toggle('hidden', !tabs); updateTabs(); }
function go(r){ state.route=r; save(); render(); }
function updateTabs(){ $$('.tab').forEach(b=>b.classList.toggle('active', b.dataset.route===state.route)); }
function appRows(mode='limits'){
  return apps.filter(a=> mode==='select' || state.selectedApps.includes(a[0]) || ['Facebook','Safari','Games'].includes(a[0])).map(([name,cls,g,time,p])=>{
    const selected = state.selectedApps.includes(name);
    if(mode==='select') return `<button class="choice ${selected?'selected':''}" onclick="toggleApp('${name}')">${icon(cls,name,g)}<div><b>${name}</b><p class="subtitle" style="margin:3px 0 0">${selected?'Included in your focus challenge':'Not tracked'}</p></div><span class="round">${selected?'✓':''}</span></button>`;
    const over = p>100;
    return `<div class="list-row" onclick="${over?`go('limitReached')`:`toast('${name} limit opened')`}">${icon(cls,name,g)}<div class="copy"><h4>${name}</h4><div class="limit-line"><div class="limit-fill ${over?'over':''}" style="width:${Math.min(p,100)}%"></div></div></div><div style="text-align:right"><b class="${over?'alert':'gold'}">${p}%</b><p class="caption">${time}<br>of ${name==='X'?'30m':'1h'}</p></div><span class="chev">›</span></div>`;
  }).join('');
}
function toggleApp(name){ const i=state.selectedApps.indexOf(name); i>-1?state.selectedApps.splice(i,1):state.selectedApps.push(name); save(); render(); }
function setGoal(goal){ state.goal=goal; save(); render(); }
function setVault(v){ state.vault=v; save(); render(); }
function setDuration(d){ state.duration=d; save(); render(); }
function addMinutes(m){ state.focusRemaining += m*60; state.spent += m*.5; save(); toast(`${m} minutes added`); go('focus'); }
function onboardWelcome(){ screen(`<div class="hero-center"><div class="brand-seal">A</div><div class="brand-word">AUREA</div><p class="subtitle" style="font-family:Georgia,serif;font-size:17px;margin:12px auto 58px;max-width:260px">Protect your attention with limits, commitment, and beautifully measured progress.</p><div class="stack"><button class="primary" onclick="go('signin')">Get Started</button><button class="ghost" onclick="state.onboarded=true;state.route='dashboard';save();render()">Preview Demo</button></div></div>`, false); }
function signin(){ screen(`${appTop('Welcome back','Sign in to continue your journey.','welcome')}<div class="stack" style="margin-top:28px"><label class="tiny">Email</label><input class="field" value="alex@aurea.app"><label class="tiny">Password</label><input class="field" type="password" value="protectyourfocus"><button class="primary" onclick="go('goals')">Sign In</button><button class="secondary"> Continue with Apple</button><p class="subtitle" style="text-align:center">By continuing, you agree to our <span class="gold">Terms</span> and <span class="gold">Privacy Policy</span>.</p></div>`, false); }
function goals(){ const goals=['Reduce screen time','Improve focus','Sleep better','Protect evenings']; screen(`${appTop('What do you want to improve?','Choose your focus. You can adjust anytime later.','signin')}<div class="choice-list">${goals.map((g,i)=>`<button class="choice ${state.goal===g?'selected':''}" onclick="setGoal('${g}')"><span class="mini-icon" style="background:#19170f;color:var(--gold);border:1px solid var(--line)">${['▥','◎','☾','☀'][i]}</span><div><b>${g}</b><p class="subtitle" style="margin:3px 0 0">${['Cut back on excess usage and take control.','Build deeper focus and get more done.','Establish healthier habits for better sleep.','Be present when it matters most.'][i]}</p></div><span class="round">${state.goal===g?'✓':''}</span></button>`).join('')}</div><div style="margin-top:28px"><button class="primary" onclick="go('apps')">Continue</button></div>`, false); }
function setupApps(){ screen(`${appTop('Select distracting apps','Choose the apps you want to limit during your focus challenge.','goals')}<div class="card list" style="margin-top:18px">${appRows('select')}</div><div style="margin-top:24px"><button class="primary" onclick="go('limitsSetup')">Continue</button></div>`, false); }
function limitsSetup(){ const rows = state.selectedApps.map(n=>apps.find(a=>a[0]===n)).map(([name,cls,g])=>`<div class="list-row">${icon(cls,name,g)}<div class="copy"><h4>${name}</h4></div><button class="circle-btn dark" style="width:32px;height:32px" onclick="state.limits['${name}']=Math.max(5,(state.limits['${name}']||30)-5);save();render()">−</button><b>${state.limits[name]||30} min</b><button class="circle-btn dark" style="width:32px;height:32px" onclick="state.limits['${name}']=(state.limits['${name}']||30)+5;save();render()">＋</button></div>`).join(''); screen(`${appTop('Set daily limits','Choose how much time you’d like for each app, every day.','apps')}<div class="card list" style="margin-top:18px">${rows}</div><div style="margin-top:24px"><button class="primary" onclick="go('vault')">Continue</button></div>`, false); }
function vault(){ screen(`${appTop('Create your Focus Vault','Lock in an amount to stay accountable. Stay within your limits and get it back.','limitsSetup')}<div class="section"><p class="tiny">Choose your vault amount</p><div class="row" style="margin-top:10px">${[20,50,100].map(v=>`<button class="choice ${state.vault===v?'selected':''}" style="flex:1;justify-content:center;min-height:54px" onclick="setVault(${v})"><b>$${v}</b></button>`).join('')}</div></div><div class="section"><p class="tiny">Challenge duration</p><div class="row" style="margin-top:10px">${[14,21].map(v=>`<button class="choice ${state.duration===v?'selected':''}" style="flex:1;justify-content:center;min-height:54px" onclick="setDuration(${v})"><b>${v} days</b></button>`).join('')}</div></div><div class="card pad contract-card section"><div class="check-list"><div class="check">Extra minutes use your locked vault.</div><div class="check">Unused balance unlocks when your challenge ends.</div></div></div><div class="card pad section"><div class="between row"><span>Rate after limit</span><b class="gold">$0.50/min</b></div></div><div style="margin-top:20px"><button class="primary" onclick="go('contract')">🔒 Lock Vault</button></div>`, false); }
function contract(){ screen(`${appTop('Challenge Contract','Review your commitment.','vault')}<div class="card pad contract-card section"><div class="list-row"><span>🪙</span><div class="copy">Vault Amount</div><b class="gold">${money(state.vault)}</b></div><div class="list-row"><span>🗓</span><div class="copy">Duration</div><b>${state.duration} days</b></div><div class="list-row"><span>⏱</span><div class="copy">Rate After Limit</div><b>$0.50/min</b></div><div class="list-row"><span>▦</span><div class="copy">Tracked Apps</div><b>${state.selectedApps.length}</b></div><div class="list-row"><span>📅</span><div class="copy">Unlock Date</div><b>May 26, 2025</b></div></div><div class="check-list"><div class="check">Funds are locked until the challenge ends.</div><div class="check">Over-limit minutes draw from your vault at $0.50/min.</div><div class="check">Unused balance unlocks when your challenge ends.</div><div class="check">Customer support is available if you need help.</div></div><button class="primary" onclick="state.onboarded=true;state.route='dashboard';save();render()">🔒 I Agree, Lock Vault</button>`, false); }
function dashboard(){ screen(`${appTop(`Good evening, <span class="gold">${state.name}</span>`,`A little more intention, every day.`,false,'<button class="icon-btn" onclick="toast(\'Notifications paused\')">♧</button>')}<div class="dashboard-hero row between"><div><p class="tiny">Today’s screen time</p><div class="big-num">4h 32m</div><p class="caption">vs yesterday <span class="gold">↓ 18%</span></p><p class="tiny" style="margin-top:14px">Remaining budget</p><h3 class="serif gold" style="font-size:22px">1h 28m</h3><div class="limit-line" style="width:120px"><div class="limit-fill" style="width:36%"></div></div></div><div class="score-ring" style="--p:82"><div class="score-inner"><b>82</b><small>Great</small></div></div></div><div class="metric-grid section"><div class="metric"><small>Pickups</small><strong>24</strong><span>↓ 21%</span></div><div class="metric"><small>Focus sessions</small><strong>2</strong><span>↑ 1 session</span></div><div class="metric"><small>Late-night use</small><strong>23m</strong><span>↓ 37%</span></div></div><div class="card pad section"><div class="section-head"><h3>Today’s Activity</h3><span class="pill">Today⌄</span></div><div class="chart">${[8,15,38,26,62,88,70,24,16,8,33,74,62,20].map(h=>`<i class="bar" style="height:${h}%"></i>`).join('')}</div></div><div class="row section"><div class="card pad" style="flex:1"><p class="tiny">Vault balance</p><h3 class="gold serif">${money(state.vault-state.spent)}</h3></div><div class="card pad" style="flex:1"><p class="tiny">Protected this week</p><h3 class="gold serif">${money(state.protected)}</h3></div></div><div class="card list section"><div class="list-row" onclick="go('focus')"><span class="mini-icon" style="background:var(--gold-soft);color:var(--gold)">◎</span><div class="copy"><h4>Start a focus session</h4><p>Block distractions and get more done.</p></div><span class="chev">›</span></div><div class="list-row" onclick="go('windDown')"><span class="mini-icon" style="background:var(--gold-soft);color:var(--gold)">☾</span><div class="copy"><h4>Power down earlier tonight</h4><p>Try a digital sunset 30–60 min before bed.</p></div><span class="chev">›</span></div></div>`); }
function limitsPage(){ screen(`${appTop('App Limits','Stay within your plan. Protect your time.',false,'<button class="icon-btn" onclick="toast(\'Limits synced\')">↻</button>')}<div class="seg section"><button class="active">Daily</button><button>Weekly</button></div><div class="card list section">${appRows('limits')}</div><div class="card pad section row"><span class="mini-icon" style="background:var(--gold-soft);color:var(--gold)">◇</span><p class="subtitle" style="margin:0">Over-limit use draws from your vault. Stay mindful to protect more.</p></div>`); }
function focus(){ const m=Math.floor(state.focusRemaining/60), s=String(state.focusRemaining%60).padStart(2,'0'); screen(`${appTop('', '', 'dashboard','<button class="icon-btn" onclick="go(\'settings\')">⚙</button>')}<div class="focus-screen"><div class="focus-wrap"><div style="font-size:38px;color:var(--gold)">⌘</div><h1 class="title">Deep Focus</h1><p class="subtitle">Stay present. Do your best work.</p><div class="focus-ring" style="--p:${(state.focusRemaining/2700)*100}"><div class="focus-time">${m}:${s}<small>of 45 min</small></div></div><span class="pill gold">Deep Focus⌄</span><div class="focus-actions"><button class="circle-btn" onclick="toggleFocus()">${state.focusRunning?'Ⅱ':'▶'}</button><button class="circle-btn" onclick="state.focusRunning=false;state.focusRemaining=1476;save();render()">■</button><button class="circle-btn dark" onclick="addMinutes(10)">＋10</button></div></div><div class="card list"><div class="list-row"><span>⌘</span><div class="copy">Distractions blocked</div><b>14</b></div><div class="list-row"><span>♧</span><div class="copy">Notifications paused</div><b>23</b></div><div class="list-row"><span>▧</span><div class="copy">App opens blocked</div><b>7</b></div><div class="list-row"><span>◷</span><div class="copy">Time saved</div><b>34m</b></div></div></div>`); }
function toggleFocus(){ state.focusRunning=!state.focusRunning; save(); render(); tick(); }
function tick(){ clearInterval(timer); if(!state.focusRunning) return; timer=setInterval(()=>{ if(state.focusRemaining>0){state.focusRemaining--; save(); if(state.route==='focus') render();}else{state.focusRunning=false; go('completion')} },1000); }
function limitReached(){ screen(`<div class="modal-screen"><div class="warning">!</div><h1 class="title">You reached your limit<br>for <span class="gold">Instagram</span> today.</h1><p class="subtitle" style="margin:34px 0">Continue using Instagram<br>for <span class="gold">$0.50/min</span> from your Focus Vault.</p><div class="stack"><button class="primary" onclick="go('focus')">◎ Start Focus Session</button><button class="secondary" onclick="go('extraMinutes')">▣ Buy Extra Minutes</button><button class="ghost" onclick="go('dashboard')">Back Out</button></div><div class="card pad section between row"><span>Vault balance</span><b class="gold">${money(state.vault-state.spent)}</b></div></div>`, false); }
function extraMinutes(){ screen(`${appTop('Buy extra minutes','Continue beyond your limit from your Focus Vault.','limitReached')}<div class="price-grid section">${[5,10,15].map((m,i)=>`<button class="price" onclick="addMinutes(${m})"><div><b style="color:var(--text);font-size:16px">◷ ${m} extra minutes</b>${i===1?'<p class="gold" style="font-size:12px">Most popular</p>':''}</div><b>$${(m*.5).toFixed(2)}</b></button>`).join('')}<button class="price" onclick="toast('Custom amount coming next')"><div><b style="color:var(--text);font-size:16px">◷ Custom amount</b><p class="caption">Set your own minutes</p></div><span class="chev">›</span></button></div><div class="card pad section row between"><div><p class="caption">Current rate</p><h2 class="serif">$0.50/min</h2></div><div><p class="caption">Source</p><span class="pill">▣ From vault</span></div></div><button class="primary" style="margin-top:20px" onclick="addMinutes(10)">Add Minutes</button>`, false); }
function windDown(){ screen(`${appTop('', '', 'dashboard')}<div class="wind-card card section"><div class="moon">☾</div><h1 class="title">Wind <span class="gold">Down</span></h1><p class="subtitle">A calming routine to help you unwind and sleep better.</p><div class="card list section"><div class="toggle-row"><div><p class="tiny">Start time</p><h2 class="serif gold">9:30 <small style="color:var(--text);font-size:16px">PM</small></h2></div><span class="pill">Edit</span></div>${['Quiet Mode|Silence notifications','No Social After 10 PM|Block social apps','Reading Mode|Encourage offline reading','Sleep Prep|Dim screen & enable Do Not Disturb'].map(x=>{let [a,b]=x.split('|'); return `<div class="toggle-row"><div><b>${a}</b><p class="caption">${b}</p></div><span class="toggle">✓</span></div>`}).join('')}</div><button class="primary" style="margin-top:18px" onclick="toast('Wind Down started')">Start Wind Down</button><button class="ghost" style="margin-top:10px">Preview Routine</button></div>`); }
function insights(){ screen(`${appTop('Insights','This week',false,'<button class="icon-btn">♧</button>')}<div class="card insight-chart section"><div class="between row"><div><p class="tiny">Screen time</p><h1 class="title">4h 12m</h1></div><span class="gold">↓ 16%</span></div><div class="weekly-bars">${[['MON',45],['TUE',62],['WED',78],['THU',68],['FRI',65],['SAT',46],['SUN',28]].map(d=>`<div class="daybar"><i style="height:${d[1]}px"></i><small>${d[0]}</small></div>`).join('')}</div></div><div class="metric-grid section"><div class="card pad"><p class="tiny">Focus time</p><h2 class="serif">2h 48m</h2><p class="gold">↑ 20%</p></div><div class="card pad"><p class="tiny">Late-night use</p><h2 class="serif">58m</h2><p class="gold">↓ 31%</p></div><div class="card pad"><p class="tiny">Pickups</p><h2 class="serif">28</h2><p class="gold">↓ 22%</p></div></div><div class="card list section"><div class="section-head" style="padding:14px 14px 0"><h3>Top distracting apps</h3><span class="caption">Total time</span></div>${[['Instagram','ig','◎','1h 05m',82],['YouTube','yt','▶','45m',56],['TikTok','tt','♪','32m',42]].map(([n,c,g,t,p])=>`<div class="list-row">${icon(c,n,g)}<div class="copy"><h4>${n}</h4><div class="limit-line"><div class="limit-fill" style="width:${p}%"></div></div></div><b>${t}</b></div>`).join('')}</div><div class="card pad section row" onclick="toast('Best focus window saved')"><span class="mini-icon" style="background:var(--gold-soft);color:var(--gold)">☀</span><div><p class="caption">Best focus window</p><h3 class="serif">9:00 AM – 12:00 PM</h3><p class="caption">Most focused time this week</p></div><span class="chev" style="margin-left:auto">›</span></div>`); }
function challenge(){ screen(`${appTop('7-Day Focus Challenge','Focus more. Unlock more.', 'dashboard','<button class="icon-btn">🏆</button>')}<div class="card pad section" style="text-align:center"><div class="progress-ring" style="--p:71;margin:0 auto;width:170px;height:170px"><div class="score-inner"><b style="font-size:58px">5/7</b><small>71% Complete</small></div></div><div class="challenge-days">${['M','T','W','T','F','S','S'].map((d,i)=>`<div><small class="caption">${d}</small><span class="day ${i<5?'done':''}">${i<5?'✓':''}</span></div>`).join('')}</div></div><div class="row section"><div class="card pad" style="flex:1"><p class="tiny">Current streak</p><h2 class="serif gold">5 Days</h2><p class="caption">Keep it going</p></div><div class="card pad" style="flex:1"><p class="tiny">Best streak</p><h2 class="serif">8 Days</h2><p class="caption">Achieved 2 weeks ago</p></div></div><div class="card pad section"><p class="tiny">Focus Vault</p><div class="between row"><h2 class="serif">${money(state.vault-state.spent)}</h2><div style="text-align:right"><p class="caption">Projected unlock</p><b>May 25, 2025</b></div></div><div class="limit-line" style="height:9px;margin-top:14px"><div class="limit-fill" style="width:61%"></div></div><p class="caption" style="margin-top:8px;text-align:center">Stay consistent to unlock your vault.</p></div>`); }
function report(){ screen(`${appTop('Weekly Report','Jun 9 – Jun 15, 2025')}<div class="card pad section"><div class="between row"><div><p class="serif" style="font-size:19px">You reclaimed <span class="gold">6h</span> this week.</p><p class="caption">Consistency compounds.</p></div><div class="score-ring" style="--p:84;width:112px;height:112px"><div class="score-inner"><b>84</b><small>Great</small></div></div></div></div><div class="metric-grid section"><div class="card pad"><p class="tiny">Focus sessions</p><h2 class="serif">12</h2><p class="gold">↑ 3</p></div><div class="card pad"><p class="tiny">Late-night use</p><h2 class="serif">1h 42m</h2><p class="gold">↓ 32%</p></div><div class="card pad"><p class="tiny">Time reclaimed</p><h2 class="serif">6h 0m</h2><p class="gold">↑ 20%</p></div></div><div class="card pad section"><p class="tiny">Time reclaimed trend</p><div class="report-chart section">${[34,48,68,83,100].map(h=>`<i style="height:${h}%"></i>`).join('')}</div></div><div class="row section"><div class="card pad" style="flex:1"><p class="tiny">Protected this week</p><h3 class="gold serif">${money(18)}</h3></div><div class="card pad" style="flex:1"><p class="tiny">Spent extra minutes</p><h3 class="gold serif">${money(state.spent)}</h3></div></div>`); }
function settings(){ screen(`${appTop('Settings','',false)}<div class="card settings-profile section"><div class="avatar">AM</div><div class="copy"><h2 class="serif">Alex Morgan</h2><p class="caption">alex@aurea.app</p></div><span class="chev">›</span></div><div class="card list section">${['Notifications|Manage alerts and reminders','Focus Modes|Customize your focus experience','Wind Down|Evening routines and digital sunset','App Limits|Set daily limits by category','Privacy & Data|Control your data and permissions','Devices|Manage connected devices'].map((x,i)=>{let [a,b]=x.split('|'); return `<div class="list-row" onclick="${i===1?'go(\'focus\')':i===2?'go(\'windDown\')':i===3?'go(\'limits\')':'toast(\''+a+' opened\')'}"><span class="mini-icon" style="background:transparent;color:var(--gold);border:0">${['♧','☾','☾','⌛','🔒','▯'][i]}</span><div class="copy"><h4>${a}</h4><p>${b}</p></div><span class="chev">›</span></div>`}).join('')}</div><div class="card list section"><div class="list-row"><span class="mini-icon" style="background:transparent;color:var(--gold);border:0">◉</span><div class="copy"><h4>Appearance</h4><p>Theme, display, and preferences</p></div><span class="chev">›</span></div><div class="list-row"><span class="mini-icon" style="background:transparent;color:var(--gold);border:0">▭</span><div class="copy"><h4>Payment Method</h4><p>Manage your card and billing</p></div><span class="chev">›</span></div></div><button class="ghost section" onclick="localStorage.removeItem('aurea_state');location.reload()">Reset Demo</button>`); }
function completion(){ screen(`<div class="modal-screen"><div class="complete-lock">🔒</div><h1 class="title">Challenge Complete</h1><p class="subtitle">Your challenge is complete.<br>You stayed committed and built something that lasts.</p><div class="card pad section"><div class="list-row"><span>💼</span><div class="copy">Unlocked balance</div><b class="gold">${money(state.vault-state.spent)}</b></div><div class="list-row"><span>◷</span><div class="copy">Extra-minute spend</div><b class="gold">${money(state.spent)}</b></div><div class="list-row"><span>◷</span><div class="copy">Time reclaimed</div><b class="gold">5h 10m</b></div></div><p class="subtitle" style="margin:18px 0">Discipline today. Freedom tomorrow.<br>Well done, ${state.name}.</p><div class="stack"><button class="primary" onclick="toast('Funds withdrawal started')">Withdraw Funds</button><button class="secondary" onclick="go('vault')">Start New Challenge</button></div></div>`, false); }
function render(){
  clearInterval(timer); if(state.focusRunning) tick();
  const r=state.route;
  if(!state.onboarded){ ({welcome:onboardWelcome, signin, goals, apps:setupApps, limitsSetup, vault, contract}[r]||onboardWelcome)(); return; }
  ({dashboard, limits:limitsPage, focus, limitReached, extraMinutes, windDown, insights, challenge, report, settings, completion, vault, contract}[r]||dashboard)();
}
$$('.tab').forEach(b=>b.addEventListener('click',()=>go(b.dataset.route)));
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
setTimeout(()=>$('#splash').classList.add('done'),900);
render();
